
name: Terraform Apply

on:
  push:
    branches:
      - test-terraform

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.check_commit_message.outputs.deploy }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        id: check_commit_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Enroll"* ]]; then
            echo "Contains 'Enroll'"
            echo "DEPLOY=true" >> $GITHUB_ENV
          else
            echo "Does not contain 'Enroll'"
            echo "deploy=false" >> $GITHUB_ENV
          fi

  terraform:
    runs-on: ubuntu-latest
    needs: check_commit_message
    if: needs.check_commit_message.outputs.deploy == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: HashiCorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./test-terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./test-terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./test-terraform
        env:
          TF_VAR_CTRL_URL: ${{ secrets.TF_VAR_CTRL_URL }}
          TF_VAR_USER_NAME: ${{ secrets.TF_VAR_USER_NAME }}
          TF_VAR_USER_PW: ${{ secrets.TF_VAR_USER_PW }}
          TF_VAR_TENANT_NAME: ${{ secrets.TF_VAR_TENANT_NAME }}


      - name: Commit tfstate file
        run: |
          rm -rf .lock
          git config --local user.email "ksun4131@gmail.com"
          git config --local user.name "KwonSunJae"
          git add .
          git commit -m "Update tfstate file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./test-terraform
